//! Micro-benchmarks for the maze engine hot path.
//!
//! Run: cargo bench -p maze-core

use criterion::{black_box, criterion_group, criterion_main, Criterion};
use maze_core::base64;
use maze_core::maze::{replay, MAX_COOKIE_LEN, MAX_PATH_LEN};

/// A legal path of exactly `len` moves: repeats the in-place loop rl, so
/// every prefix stays on open corridor cells and never reaches the exit.
fn legal_path(len: usize) -> String {
    let mut p = "rl".repeat(len / 2 + 1);
    p.truncate(len);
    p
}

/// The surveyed solution, encoded as the cookie value would be.
fn solution_cookie() -> String {
    let mut s = String::new();
    for (ch, n) in [
('r', 6),
        ('d', 2),
        ('l', 6),
        ('d', 6),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 4),
        ('r', 6),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 4),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 8),
        ('d', 2),
        ('r', 6),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 6),
        ('u', 2),
        ('r', 4),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 8),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 6),
        ('r', 2),
        ('d', 4),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 4),
        ('d', 4),
        ('l', 2),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('l', 6),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 12),
        ('r', 2),
        ('u', 2),
        ('l', 4),
        ('d', 12),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 6),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 4),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 6),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 4),
        ('l', 4),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('d', 4),
        ('r', 6),
        ('u', 4),
        ('r', 4),
        ('u', 4),
        ('l', 4),
        ('d', 2),
        ('l', 2),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 8),
        ('u', 2),
        ('l', 10),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('l', 2),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('d', 4),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 8),
        ('l', 4),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('r', 4),
        ('d', 8),
        ('r', 6),
        ('u', 4),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 8),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 6),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 4),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 8),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('l', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 8),
        ('r', 2),
        ('d', 2),
        ('r', 6),
        ('d', 2),
        ('r', 4),
        ('d', 4),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('l', 4),
        ('d', 2),
        ('l', 4),
        ('u', 4),
        ('l', 4),
        ('u', 4),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 4),
        ('r', 6),
        ('d', 4),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 6),
        ('d', 2),
        ('l', 2),
        ('d', 8),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('d', 6),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 6),
        ('l', 4),
        ('u', 4),
        ('l', 2),
        ('u', 4),
        ('r', 4),
        ('u', 4),
        ('l', 6),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 4),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 10),
        ('l', 8),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 6),
        ('r', 4),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 4),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 6),
        ('l', 2),
        ('d', 2),
        ('r', 8),
        ('d', 2),
        ('l', 16),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 8),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 6),
        ('u', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 6),
        ('u', 2),
        ('r', 2),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('u', 4),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 2),
        ('l', 8),
        ('d', 4),
        ('l', 2),
        ('u', 4),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 2),
        ('d', 6),
        ('l', 8),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 4),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('d', 6),
        ('r', 6),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('d', 6),
        ('r', 14),
        ('u', 2),
        ('l', 8),
        ('u', 2),
        ('r', 6),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 12),
        ('d', 2),
        ('r', 2),
        ('d', 8),
        ('l', 4),
        ('d', 2),
        ('r', 5),
    ] {
        for _ in 0..n {
            s.push(ch);
        }
    }
    let mut buf = [0u8; MAX_COOKIE_LEN];
    let n = base64::encode_into(s.as_bytes(), &mut buf).unwrap();
    String::from_utf8(buf[..n].to_vec()).unwrap()
}

fn bench_core(c: &mut Criterion) {
    let mut g = c.benchmark_group("maze/replay");
    for len in [0usize, 10, 100, 1000, 3072] {
        let path = legal_path(len);
        g.bench_function(format!("len_{len}"), |b| {
            b.iter(|| replay(black_box(path.as_bytes())))
        });
    }
    g.finish();

    let mut g = c.benchmark_group("maze/base64");
    let sol = solution_cookie(); // 1944-char cookie of the 1457-move solution
    // a real 4096-char cookie: 3072 legal moves encode to exactly 4096 chars
    let cookie4096 = {
        let raw = legal_path(3072);
        let mut buf = [0u8; MAX_COOKIE_LEN];
        let n = base64::encode_into(raw.as_bytes(), &mut buf).unwrap();
        buf[..n].to_vec()
    };
    let mut out_path = [0u8; MAX_PATH_LEN];
    let mut out_cookie = [0u8; MAX_COOKIE_LEN];
    g.bench_function("decode_cookie48", |b| {
        b.iter(|| base64::decode_into(black_box(sol.as_bytes()), black_box(&mut out_path)).unwrap())
    });
    g.bench_function("decode_cookie4096", |b| {
        b.iter(|| {
            base64::decode_into(black_box(&cookie4096), black_box(&mut out_path)).unwrap()
        })
    });
    g.bench_function("encode_cookie48", |b| {
        b.iter(|| {
            let raw = sol.as_bytes();
            base64::encode_into(black_box(raw), black_box(&mut out_cookie)).unwrap()
        })
    });
    g.bench_function("encode_path3072", |b| {
        let raw = legal_path(3072).into_bytes();
        b.iter(|| base64::encode_into(black_box(&raw), black_box(&mut out_cookie)).unwrap())
    });
    g.finish();
}

criterion_group!(benches, bench_core);
criterion_main!(benches);