//! Cross-module spec tests: the full cookie pipeline (encode -> decode ->
//! replay) and maze connectivity guarantees.

use maze_core::base64;
use maze_core::maze::{cell_at, replay, Outcome, EXIT, H, MAX_COOKIE_LEN, MAX_PATH_LEN, START, W};

/// The known-good shortest solution to the bundled maze (1457 lowercase
/// moves, as the Daedalus UI writes them), surveyed by the mapper. Written
/// as (letter, run length) pairs to keep this file readable.
fn solution() -> Vec<u8> {
    let mut s = String::new();
    for (c, n) in [
        ('r', 6),
        ('d', 2),
        ('l', 6),
        ('d', 6),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 4),
        ('r', 6),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 4),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 8),
        ('d', 2),
        ('r', 6),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 6),
        ('u', 2),
        ('r', 4),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 8),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 6),
        ('r', 2),
        ('d', 4),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 4),
        ('d', 4),
        ('l', 2),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('l', 6),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 12),
        ('r', 2),
        ('u', 2),
        ('l', 4),
        ('d', 12),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 6),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 4),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 6),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 4),
        ('l', 4),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('d', 4),
        ('r', 6),
        ('u', 4),
        ('r', 4),
        ('u', 4),
        ('l', 4),
        ('d', 2),
        ('l', 2),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 8),
        ('u', 2),
        ('l', 10),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('l', 2),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('d', 4),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 8),
        ('l', 4),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('r', 4),
        ('d', 8),
        ('r', 6),
        ('u', 4),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 8),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 6),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 4),
        ('u', 2),
        ('r', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 8),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('l', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 8),
        ('r', 2),
        ('d', 2),
        ('r', 6),
        ('d', 2),
        ('r', 4),
        ('d', 4),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('l', 2),
        ('u', 4),
        ('r', 2),
        ('u', 2),
        ('l', 4),
        ('d', 2),
        ('l', 4),
        ('u', 4),
        ('l', 4),
        ('u', 4),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 4),
        ('d', 4),
        ('r', 6),
        ('d', 4),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('r', 6),
        ('d', 2),
        ('l', 2),
        ('d', 8),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('d', 6),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 6),
        ('l', 4),
        ('u', 4),
        ('l', 2),
        ('u', 4),
        ('r', 4),
        ('u', 4),
        ('l', 6),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 4),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 10),
        ('l', 8),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('l', 6),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 6),
        ('r', 4),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 2),
        ('d', 4),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('d', 2),
        ('r', 2),
        ('d', 6),
        ('l', 2),
        ('d', 2),
        ('r', 8),
        ('d', 2),
        ('l', 16),
        ('d', 2),
        ('l', 4),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 8),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('d', 2),
        ('r', 2),
        ('d', 2),
        ('l', 6),
        ('u', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 6),
        ('u', 2),
        ('r', 2),
        ('d', 6),
        ('r', 2),
        ('d', 2),
        ('l', 4),
        ('u', 4),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('u', 2),
        ('l', 8),
        ('d', 4),
        ('l', 2),
        ('u', 4),
        ('l', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 2),
        ('d', 6),
        ('l', 8),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('l', 4),
        ('d', 4),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('d', 6),
        ('r', 6),
        ('u', 2),
        ('r', 4),
        ('d', 2),
        ('r', 4),
        ('u', 2),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('r', 4),
        ('d', 2),
        ('l', 2),
        ('d', 2),
        ('r', 4),
        ('u', 2),
        ('r', 2),
        ('d', 6),
        ('r', 14),
        ('u', 2),
        ('l', 8),
        ('u', 2),
        ('r', 6),
        ('u', 2),
        ('r', 2),
        ('d', 2),
        ('r', 2),
        ('d', 4),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 4),
        ('l', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 2),
        ('u', 2),
        ('r', 12),
        ('d', 2),
        ('r', 2),
        ('d', 8),
        ('l', 4),
        ('d', 2),
        ('r', 5),
    ] {
        for _ in 0..n {
            s.push(c);
        }
    }
    s.into_bytes()
}

#[test]
fn maze_is_fully_connected() {
    // BFS from the start over all walkable cells.
    let mut seen = [false; W * H];
    let mut queue = vec![START];
    seen[START] = true;
    let mut qi = 0usize;
    while qi < queue.len() {
        let p = queue[qi];
        qi += 1;
        let x = p % W;
        let y = p / W;
        let nbrs = [
            (x as isize, y as isize - 1),
            (x as isize, y as isize + 1),
            (x as isize - 1, y as isize),
            (x as isize + 1, y as isize),
        ];
        for (nx, ny) in nbrs {
            if nx < 0 || ny < 0 || nx >= W as isize || ny >= H as isize {
                continue;
            }
            let idx = ny as usize * W + nx as usize;
            if cell_at(nx as usize, ny as usize) != 1 && !seen[idx] {
                seen[idx] = true;
                queue.push(idx);
            }
        }
    }
    let mut open = 0usize;
    for y in 0..H {
        for x in 0..W {
            if cell_at(x, y) != 1 {
                open += 1;
            }
        }
    }
    assert_eq!(queue.len(), open, "every walkable cell must be reachable");
    assert!(seen[EXIT], "exit must be reachable from start");
}

#[test]
fn cookie_pipeline_solves() {
    // Exactly what the browser and the server will do, end to end, with no
    // heap allocation: encode the path into a cookie value, decode it back,
    // replay it.
    let p = solution();
    let mut cookie = [0u8; MAX_COOKIE_LEN];
    let cn = base64::encode_into(&p, &mut cookie).unwrap();
    assert!(cn <= MAX_COOKIE_LEN);
    let mut decoded = [0u8; MAX_PATH_LEN];
    let dn = base64::decode_into(&cookie[..cn], &mut decoded).unwrap();
    assert_eq!(&decoded[..dn], &p[..]);
    assert_eq!(replay(&decoded[..dn]), Outcome::Solved);
}

#[test]
fn uppercase_spellings_bonk_like_the_site() {
    // The site only knows the four lowercase letters; uppercase moves play
    // as walls. The lowercase solution must solve, its uppercase twin bonks
    // on the first move.
    assert_eq!(replay(b"r"), Outcome::GoingWell);
    assert_eq!(replay(b"R"), Outcome::Bonk);
    let sol = solution();
    assert_eq!(replay(&sol), Outcome::Solved);
    let upper: Vec<u8> = sol.iter().map(|&b| b.to_ascii_uppercase()).collect();
    assert_eq!(replay(&upper), Outcome::Bonk);
}