//! Router allocation audit: counts every heap allocation in the pure handler
//! for each request class and asserts tight bounds. Actual counts are printed
//! for the record; they are the numbers quoted in the README.

use std::alloc::{GlobalAlloc, Layout, System};
use std::sync::atomic::{AtomicUsize, Ordering};

use maze_core::base64;
use maze_core::maze::MAX_COOKIE_LEN;
use maze_server::bodies;
use maze_server::router::route_parts;

static ALLOCS: AtomicUsize = AtomicUsize::new(0);

struct Counting;

unsafe impl GlobalAlloc for Counting {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        ALLOCS.fetch_add(1, Ordering::Relaxed);
        System.alloc(layout)
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        System.dealloc(ptr, layout)
    }
}

#[global_allocator]
static ALLOCATOR: Counting = Counting;

fn allocs<T>(f: impl FnOnce() -> T) -> usize {
    let before = ALLOCS.load(Ordering::Relaxed);
    let _ = f();
    ALLOCS.load(Ordering::Relaxed) - before
}

fn parts(uri: &str, cookie: Option<String>) -> hyper::http::request::Parts {
    let mut b = hyper::Request::builder().method("GET").uri(uri);
    if let Some(c) = cookie {
        b = b.header("cookie", format!("path={c}"));
    }
    b.body(()).unwrap().into_parts().0
}

#[test]
fn router_allocations_are_bounded() {
    let solved_cookie = {
        let mut s = String::new();
        for (ch, n) in [
            ('r', 6),
            ('d', 2),
            ('l', 6),
            ('d', 6),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('d', 2),
            ('r', 2),
            ('u', 4),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('d', 4),
            ('r', 2),
            ('u', 4),
            ('r', 6),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 4),
            ('d', 2),
            ('l', 2),
            ('d', 4),
            ('r', 2),
            ('u', 2),
            ('r', 4),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('r', 8),
            ('d', 2),
            ('r', 6),
            ('u', 2),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 4),
            ('d', 2),
            ('r', 6),
            ('u', 2),
            ('r', 4),
            ('d', 4),
            ('l', 2),
            ('d', 2),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('d', 2),
            ('r', 4),
            ('u', 4),
            ('l', 2),
            ('u', 2),
            ('r', 4),
            ('u', 2),
            ('r', 8),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('r', 4),
            ('d', 2),
            ('l', 2),
            ('d', 6),
            ('r', 2),
            ('d', 4),
            ('l', 2),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('l', 4),
            ('d', 4),
            ('l', 2),
            ('d', 4),
            ('l', 2),
            ('d', 2),
            ('l', 6),
            ('d', 6),
            ('r', 2),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('u', 12),
            ('r', 2),
            ('u', 2),
            ('l', 4),
            ('d', 12),
            ('l', 4),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('r', 6),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('l', 4),
            ('d', 2),
            ('l', 4),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('r', 2),
            ('u', 6),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('u', 2),
            ('l', 2),
            ('d', 4),
            ('l', 4),
            ('u', 2),
            ('r', 2),
            ('u', 4),
            ('r', 2),
            ('u', 4),
            ('r', 2),
            ('d', 4),
            ('r', 6),
            ('u', 4),
            ('r', 4),
            ('u', 4),
            ('l', 4),
            ('d', 2),
            ('l', 2),
            ('u', 4),
            ('l', 2),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('r', 8),
            ('u', 2),
            ('l', 10),
            ('d', 2),
            ('l', 6),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('l', 6),
            ('d', 2),
            ('l', 2),
            ('u', 4),
            ('l', 2),
            ('u', 2),
            ('l', 2),
            ('d', 6),
            ('r', 2),
            ('d', 2),
            ('l', 4),
            ('u', 2),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('d', 4),
            ('l', 2),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('d', 2),
            ('r', 4),
            ('u', 4),
            ('r', 2),
            ('u', 2),
            ('r', 4),
            ('u', 2),
            ('r', 2),
            ('d', 4),
            ('l', 4),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('l', 2),
            ('d', 8),
            ('l', 4),
            ('d', 2),
            ('r', 4),
            ('d', 2),
            ('l', 6),
            ('d', 2),
            ('r', 4),
            ('d', 8),
            ('r', 6),
            ('u', 4),
            ('r', 4),
            ('d', 2),
            ('l', 2),
            ('d', 8),
            ('r', 2),
            ('d', 2),
            ('l', 2),
            ('d', 6),
            ('r', 2),
            ('u', 4),
            ('r', 2),
            ('u', 2),
            ('r', 4),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('l', 4),
            ('u', 2),
            ('r', 4),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 8),
            ('u', 2),
            ('r', 2),
            ('u', 4),
            ('l', 4),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('r', 2),
            ('u', 8),
            ('r', 2),
            ('d', 2),
            ('r', 6),
            ('d', 2),
            ('r', 4),
            ('d', 4),
            ('r', 2),
            ('d', 4),
            ('r', 2),
            ('u', 4),
            ('r', 2),
            ('u', 2),
            ('l', 2),
            ('u', 4),
            ('r', 2),
            ('u', 2),
            ('l', 4),
            ('d', 2),
            ('l', 4),
            ('u', 4),
            ('l', 4),
            ('u', 4),
            ('r', 2),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 4),
            ('d', 4),
            ('r', 6),
            ('d', 4),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('r', 6),
            ('d', 2),
            ('l', 2),
            ('d', 8),
            ('r', 2),
            ('d', 2),
            ('l', 4),
            ('u', 2),
            ('l', 2),
            ('d', 6),
            ('l', 2),
            ('u', 2),
            ('l', 2),
            ('d', 6),
            ('l', 4),
            ('u', 4),
            ('l', 2),
            ('u', 4),
            ('r', 4),
            ('u', 4),
            ('l', 6),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('u', 2),
            ('l', 2),
            ('d', 4),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('d', 6),
            ('r', 2),
            ('d', 2),
            ('l', 4),
            ('d', 2),
            ('r', 2),
            ('d', 10),
            ('l', 8),
            ('d', 2),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('d', 2),
            ('r', 4),
            ('d', 2),
            ('l', 6),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('r', 2),
            ('d', 4),
            ('r', 2),
            ('u', 6),
            ('r', 4),
            ('d', 6),
            ('r', 2),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('l', 2),
            ('d', 4),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('d', 4),
            ('l', 2),
            ('d', 2),
            ('r', 4),
            ('d', 2),
            ('r', 2),
            ('d', 6),
            ('l', 2),
            ('d', 2),
            ('r', 8),
            ('d', 2),
            ('l', 16),
            ('d', 2),
            ('l', 4),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('u', 8),
            ('l', 4),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('l', 4),
            ('d', 2),
            ('r', 2),
            ('d', 2),
            ('l', 6),
            ('u', 2),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('r', 6),
            ('u', 2),
            ('r', 2),
            ('d', 6),
            ('r', 2),
            ('d', 2),
            ('l', 4),
            ('u', 4),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('u', 2),
            ('l', 8),
            ('d', 4),
            ('l', 2),
            ('u', 4),
            ('l', 4),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('r', 2),
            ('d', 6),
            ('l', 8),
            ('u', 4),
            ('l', 2),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('l', 4),
            ('d', 4),
            ('l', 2),
            ('d', 2),
            ('r', 4),
            ('d', 6),
            ('r', 6),
            ('u', 2),
            ('r', 4),
            ('d', 2),
            ('r', 4),
            ('u', 2),
            ('l', 2),
            ('u', 2),
            ('r', 2),
            ('u', 4),
            ('r', 4),
            ('d', 2),
            ('l', 2),
            ('d', 2),
            ('r', 4),
            ('u', 2),
            ('r', 2),
            ('d', 6),
            ('r', 14),
            ('u', 2),
            ('l', 8),
            ('u', 2),
            ('r', 6),
            ('u', 2),
            ('r', 2),
            ('d', 2),
            ('r', 2),
            ('d', 4),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('u', 4),
            ('l', 2),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('r', 2),
            ('u', 2),
            ('r', 12),
            ('d', 2),
            ('r', 2),
            ('d', 8),
            ('l', 4),
            ('d', 2),
            ('r', 5),
        ] {
            for _ in 0..n {
                s.push(ch);
            }
        }
        let mut buf = [0u8; MAX_COOKIE_LEN];
        let n = base64::encode_into(s.as_bytes(), &mut buf).unwrap();
        String::from_utf8(buf[..n].to_vec()).unwrap()
    };

    let start = parts("/", None);
    let bonk = parts("/move", Some("dWU=".to_string())); // "ue": bonks on u
    let well = parts("/move", Some("cnI=".to_string())); // "rr": going well
    let solved = parts("/move", Some(solved_cookie));
    let missing_cookie = parts("/move", None);
    let broken_b64 = parts("/move", Some("cg".to_string()));
    let asset = parts("/static/css/index.css", None);
    let lost = parts("/reset", None);

    // Warm every page/asset cache so route measurements reflect steady state.
    let _warm = (
        bodies::start_page(),
        bodies::bonk_page(),
        bodies::well_page(),
        bodies::minotaur_page(),
        bodies::flag_page(),
    );

    let start_a = allocs(|| route_parts(&start));
    let bonk_a = allocs(|| route_parts(&bonk));
    let well_a = allocs(|| route_parts(&well));
    let solved_a = allocs(|| route_parts(&solved));
    let redirect_a = allocs(|| route_parts(&missing_cookie));
    let err500_a = allocs(|| route_parts(&broken_b64));
    let asset_a = allocs(|| route_parts(&asset));
    let lost_a = allocs(|| route_parts(&lost));
    // Page builders are cached, so warm calls are refcount clones.
    let start_page_a = allocs(bodies::start_page);
    let flag_a = allocs(bodies::flag_page);
    eprintln!(
        "alloc audit: start={start_a} bonk={bonk_a} well={well_a} solved={solved_a} \
         redirect={redirect_a} err500={err500_a} asset={asset_a} lost404={lost_a} | \
         builders: start_page(warm)={start_page_a} flag={flag_a}"
    );
    // All bodies are rodata handles; the handler itself is small and bounded.
    for (name, actual, max) in [
        ("route/start_page", start_a, 4),
        ("route/bonk_spec_pure", bonk_a, 3),
        ("route/well_spec_pure", well_a, 3),
        ("route/solved_flag", solved_a, 4),
        ("route/move_redirect_302", redirect_a, 4),
        ("route/move_broken_b64_500", err500_a, 4),
        ("route/static_asset", asset_a, 4),
        ("route/lost_404", lost_a, 4),
    ] {
        assert!(actual <= max, "{name}: {actual} > {max}");
    }
    assert_eq!(start_page_a, 0, "start_page (warm cache clone)");
    assert_eq!(flag_a, 0, "flag_page (warm cache clone)");
}
